### ISSUE TITLE
Mid circuit measurement (mz) is extremely slow and eventually halts

### ISSUE THREAD

**Issue by saurabhshivpuje** [NVIDIA/cuda-quantum#2075]
### Required prerequisites

- [X] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

In my attempt to do mid-circuit measurement (using "mz") of ancillary qubit, I don't see the expected behavior.

### Steps to reproduce the bug

@cudaq.kernel
def qrbm_reuse_ancilla(v_nodes:int, h_nodes:int, theta: list[float], coupling: list[float]):

    qubits=cudaq.qvector(v_nodes+h_nodes)
    ancilla=cudaq.qubit()

    count=0
    for i in range(v_nodes+h_nodes):
        ry(theta[count],qubits[i])
        count+=1

    count=0 
    #res = True
    # cudaq.dbg.ast.print_i64(v_nodes)

    for iter in range(v_nodes*h_nodes):
        v = iter // h_nodes
        h = (iter % h_nodes) + v_nodes
        # cudaq.dbg.ast.print_i64(v_nodes)

        ry.ctrl(coupling[count],qubits[v],qubits[h],ancilla)
        x(qubits[v])
        ry.ctrl(coupling[count+1],qubits[v],qubits[h],ancilla)
        x(qubits[v])
        x(qubits[h])
        ry.ctrl(coupling[count+1],qubits[v],qubits[h],ancilla)
        x(qubits[v])
        ry.ctrl(coupling[count],qubits[v],qubits[h],ancilla)
        x(qubits[v])
        x(qubits[h])

        res = mz(ancilla)

        if res == True:
            x(ancilla)  #Reset the qubit to |0>
            count+=2

        else: break         #When ancilla measures 0, we will have to restart the process. 

        if iter==v_nodes*h_nodes-1:
            true_res = mz(qubits)
            # cudaq.dbg.ast.print_i64(v_nodes)

### Expected behavior

This is the alternate and more efficient circuit we had designed to reduce the number of qubits expecting speed up in the calculations. However, to my observation the "mz" present in the "for" loop, which is measuring the ancilla qubit is consuming lot more processing time. Please, guide me through this or resolve the issue as early as possible. Total number of qubits we are using: 7 ( 6 + 1 ancilla). 

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**:  latest (August 10, 2024)
- **Python version**:  Python 3.10.12
- **C++ compiler**:  gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- **Operating system**:  macOS Sonoma 14.5

**Comment by bmhowe23** [comment]
Hi @saurabhshivpuje - circuits without mid-circuit can typically be simulated faster than circuits with mid-circuit measurements. The reason for this is that circuits without mid-circuit measurements can propagate a pure state vector all the way to the end of the program, and then at the end of the circuit, the state vector can be sampled an arbitrary number of times without re-running the full circuit. Since the quantum operations on the state vector are typically the expensive part of quantum circuit simulation, this is a big optimization. On the other hand, circuits with mid-circuit measurements require the simulator to re-execute the full circuit for each requested shot. Unlike circuits without mid-circuit measurements, these additional executions are required because the *circuit* being executed changes with each shot. Since the default value for the requested number of shots is 1000, this typically means that simulations involving mid-circuit measurements may be 1000x slower than circuits without them. However, if you override the number of shots to a much lower number, then the simulation will run faster (linearly with the reduction of shots count).

**Comment by saurabhshivpuje** [comment]
Yes, that clarifies why it is slow. Our attempt was to use less qubits, but we will have to tradeoff with the processing time it seems. I really appreciate this explanation of behind the scenes in details. Thank you!
