### ISSUE TITLE
Documentation missing for latest-hpc image

### ISSUE THREAD

**Issue by poojarao8** [NVIDIA/cuda-quantum#665]
It will be good to add the info about the latest-hpc image [here](https://nvidia.github.io/cuda-quantum/latest/install.html#docker-image).

**Comment by bettinaheim** [comment]
@poojarao8 The latest tag now includes all the hpc components. I will hence close the issue, since all other images are merely there to facilitate development *of* CUDA Quantum rather than *with* CUDA Quantum, and hence should be documented (only) on the GitHub repo. If you feel something is missing, please feel free to reopen.
