### ISSUE TITLE
Getting warning running python examples with the latest image

### ISSUE THREAD

**Issue by poojarao8** [NVIDIA/cuda-quantum#750]
Getting a warning `Could not find a suitable cuQuantum Python package.` with the latest image (following directions from https://nvidia.github.io/cuda-quantum/latest/install.html#docker-image), but the provided python examples seem to run okay otherwise.

**Comment by 1tnguyen** [comment]
This warning is from the code checking for the `cuquantum-cu11` Python package. This package is a dependency of our `cuda-quantum` Python package and hence will be installed if not present when installing `cuda-quantum` via `pip`. 

The docker image has a natively built cuda-quantum Python package (`opt/nvidia/cudaq`) and a system-level `cuquantum` installation (`/opt/nvidia/cuquantum`), this warning can be safely ignored. A workaround is to install the `cuquantum-cu11` Python package in the docker image since we didn't do a `pip install` of `cuda-quantum` as a package when building the image.
